# Generated by Django 2.2.5 on 2019-10-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_complaints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('hospital_id', models.IntegerField()),
                ('doctor_id', models.IntegerField()),
                ('complaint', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tbl_complaints',
            },
        ),
        migrations.CreateModel(
            name='tbl_diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_test_result_id', models.IntegerField()),
                ('patient_id', models.IntegerField()),
                ('doctor_id', models.IntegerField()),
                ('treatment_id', models.IntegerField()),
                ('opticket_id', models.IntegerField()),
                ('hospital_id', models.IntegerField()),
                ('diagnosis1', models.CharField(max_length=500)),
                ('medicines', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'tbl_diagnosis',
            },
        ),
        migrations.CreateModel(
            name='tbl_hos_cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'tbl_hos_cat',
            },
        ),
        migrations.CreateModel(
            name='tbl_hos_man',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField()),
                ('hos_name', models.CharField(max_length=30)),
                ('hos_address', models.CharField(max_length=500)),
                ('hos_email', models.CharField(max_length=30)),
                ('hos_phone', models.IntegerField()),
                ('hos_local_body', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tbl_hos_man',
            },
        ),
        migrations.CreateModel(
            name='tbl_lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField()),
                ('hospital_id', models.IntegerField()),
                ('lab_phone', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_lab',
            },
        ),
        migrations.CreateModel(
            name='tbl_lab_test_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_id', models.IntegerField()),
                ('patient_id', models.IntegerField()),
                ('doctor_id', models.IntegerField()),
                ('treatment_id', models.IntegerField()),
                ('hospital_id', models.IntegerField()),
                ('test_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tbl_lab_test_request',
            },
        ),
        migrations.CreateModel(
            name='tbl_lab_test_result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_id', models.IntegerField()),
                ('lab_test_request_id', models.IntegerField()),
                ('patient_id', models.IntegerField()),
                ('doctor_id', models.IntegerField()),
                ('treatment_id', models.IntegerField()),
                ('test_name_id', models.IntegerField()),
                ('lab_result', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'tbl_lab_test_result',
            },
        ),
        migrations.CreateModel(
            name='tbl_messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('doctor_id', models.IntegerField()),
                ('hospital_id', models.IntegerField()),
                ('message', models.CharField(max_length=500)),
                ('msg_date', models.DateField()),
                ('msg_time', models.IntegerField()),
                ('status', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'tbl_messages',
            },
        ),
        migrations.CreateModel(
            name='tbl_notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(max_length=30)),
                ('noti_date', models.DateField()),
                ('noti_status', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tbl_notification',
            },
        ),
        migrations.CreateModel(
            name='tbl_opticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_id', models.IntegerField()),
                ('patient_id', models.IntegerField()),
                ('doctor_id', models.IntegerField()),
                ('op_date', models.DateField()),
            ],
            options={
                'db_table': 'tbl_opticket',
            },
        ),
        migrations.CreateModel(
            name='tbl_patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_id', models.IntegerField()),
                ('pat_name', models.CharField(max_length=30)),
                ('pat_address', models.CharField(max_length=30)),
                ('pat_gender', models.CharField(max_length=30)),
                ('pat_email', models.CharField(max_length=30)),
                ('pat_phone', models.IntegerField()),
                ('pat_dob', models.DateField()),
                ('pat_photo', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'tbl_patient',
            },
        ),
        migrations.CreateModel(
            name='tbl_referral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('hospital_id', models.IntegerField()),
                ('referred_hos_id', models.IntegerField()),
                ('doctor_id', models.IntegerField()),
                ('doctor_views', models.CharField(max_length=500)),
                ('ref_date', models.DateField()),
            ],
            options={
                'db_table': 'tbl_referral',
            },
        ),
        migrations.CreateModel(
            name='tbl_staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField()),
                ('hospital_id', models.IntegerField()),
                ('staff_role', models.CharField(max_length=30)),
                ('staff_specialization', models.CharField(max_length=30)),
                ('staff_name', models.CharField(max_length=30)),
                ('staff_address', models.CharField(max_length=500)),
                ('staff_email', models.CharField(max_length=30)),
                ('staff_phone', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_staff',
            },
        ),
        migrations.CreateModel(
            name='tbl_treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.IntegerField()),
                ('patient_id', models.IntegerField()),
                ('hospital_id', models.IntegerField()),
                ('opticket_id', models.IntegerField()),
                ('diagnosis', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'tbl_treatment',
            },
        ),
    ]
