# Generated by Django 2.2.5 on 2019-10-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_tbl_complaints_tbl_diagnosis_tbl_hos_cat_tbl_hos_man_tbl_lab_tbl_lab_test_request_tbl_lab_test_resul'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_mcpatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_id', models.IntegerField()),
                ('pat_name', models.CharField(max_length=30)),
                ('pat_address', models.CharField(max_length=30)),
                ('pat_gender', models.CharField(max_length=30)),
                ('pat_email', models.CharField(max_length=30)),
                ('pat_phone', models.IntegerField()),
                ('pat_dob', models.DateField()),
                ('pat_photo', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'tbl_mcpatient',
            },
        ),
    ]
