# Generated by Django 2.2.5 on 2019-10-24 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_tbl_staff_staff_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_notification',
            name='noti_date',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='tbl_opticket',
            name='op_date',
            field=models.CharField(max_length=30),
        ),
    ]
