# Generated by Django 2.2.5 on 2019-10-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0005_auto_20191024_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_treatment',
            name='patient_name',
            field=models.CharField(default='null', max_length=30),
            preserve_default=False,
        ),
    ]
