# Generated by Django 2.2.5 on 2019-10-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0007_tbl_diagnosis_patient_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_lab_test_result',
            name='test_name_id',
        ),
        migrations.AddField(
            model_name='tbl_lab_test_result',
            name='test_name',
            field=models.CharField(default='null', max_length=30),
            preserve_default=False,
        ),
    ]
