# Generated by Django 2.2.5 on 2019-10-25 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0008_auto_20191024_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_referral',
            name='ref_date',
            field=models.CharField(max_length=30),
        ),
    ]
