# Generated by Django 2.2.5 on 2019-11-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0010_tbl_patient_pat_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_hos_man',
            name='hos_phone',
            field=models.CharField(max_length=30),
        ),
    ]
