# Generated by Django 2.2.5 on 2019-11-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0011_auto_20191125_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_lab',
            name='lab_phone',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='tbl_patient',
            name='pat_phone',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='tbl_staff',
            name='staff_phone',
            field=models.CharField(max_length=30),
        ),
    ]
