# Generated by Django 2.2.5 on 2019-11-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0012_auto_20191125_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_diagnosis',
            name='lab_test_result_id',
            field=models.CharField(max_length=30),
        ),
    ]
