# Generated by Django 2.2.5 on 2019-11-28 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0013_auto_20191128_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_lab_test_request',
            name='patient_id',
        ),
    ]
